org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.161.0+26.3
hikari_version=7.1.0
mysql_connector_version=26.7.0
flyway_version=13.5.0
h2_version=2.5.250

mod_version=0.1.5
maven_group=cn.contribution
archives_base_name=CSU-YSU-contribution-system
